# Generated by Django 5.1.2 on 2024-10-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
    ]
