# Generated by Django 5.1.2 on 2024-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
