# Generated by Django 5.1.2 on 2024-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="good",
            options={},
        ),
        migrations.RemoveField(
            model_name="category",
            name="group",
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="goods/"),
        ),
        migrations.AlterField(
            model_name="good",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="good",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
