# Generated by Django 5.1.2 on 2024-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_attribute_attributevalue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="category",
        ),
        migrations.AddField(
            model_name="attribute",
            name="categories",
            field=models.ManyToManyField(
                related_name="attributes",
                to="goods.category",
                verbose_name="Categories",
            ),
        ),
    ]
