# Generated by Django 5.1.2 on 2024-10-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_remove_attribute_category_attribute_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"verbose_name": "Attribute", "verbose_name_plural": "Attributes"},
        ),
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "verbose_name": "Attribute Value",
                "verbose_name_plural": "Attribute Values",
            },
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Brand", "verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="good",
            options={"verbose_name": "Good", "verbose_name_plural": "Goods"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Brand Name"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Category Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods",
                to="goods.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goods",
                to="goods.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="good",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goods/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Good Name"),
        ),
        migrations.AlterField(
            model_name="good",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Group Name"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="Slug"),
        ),
    ]
