# Generated by Django 5.1.2 on 2024-10-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_attribute_options_alter_attributevalue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="goods.group",
                verbose_name="Group",
            ),
        ),
    ]
