# Generated by Django 5.1.2 on 2024-10-23 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_category_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="sale_percent",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Sale Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
