# Generated by Django 5.1.2 on 2024-10-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_good_sale_percent_alter_good_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
