# Generated by Django 5.1.2 on 2024-10-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_good_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                default="Unknown Brand", max_length=255, verbose_name="Brand Name"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                blank=True, default="unknown-brand", max_length=255, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="categories",
                to="goods.group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="Unknown Category", max_length=255, verbose_name="Category Name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="unknown-category",
                max_length=255,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="goods",
                to="goods.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="goods",
                to="goods.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="name",
            field=models.CharField(
                default="Unknown Product", max_length=255, verbose_name="Good Name"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="slug",
            field=models.SlugField(
                default="unknown-product",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                default="Unknown Group", max_length=255, verbose_name="Group Name"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                default="unknown-group", max_length=255, verbose_name="Slug"
            ),
        ),
    ]
