# Generated by Django 5.1.2 on 2024-10-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_alter_brand_name_alter_brand_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="slug",
            field=models.SlugField(
                default="unknown-product",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
