# Generated by Django 5.1.2 on 2024-10-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0011_alter_good_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_svg",
            field=models.TextField(blank=True, null=True),
        ),
    ]
