# Generated by Django 5.1.2 on 2024-10-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0012_category_icon_svg"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
