# Generated by Django 5.1.2 on 2024-11-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0013_attribute_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together={("good", "attribute")},
        ),
    ]
