# Generated by Django 5.1.2 on 2024-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0014_alter_attributevalue_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="final_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Final Price",
            ),
        ),
    ]
