# Generated by Django 5.1.2 on 2024-11-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0015_good_final_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "ordering": ["group__order", "order", "name"],
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "ordering": ["attribute__group__order", "attribute__order"],
                "verbose_name": "Attribute Value",
                "verbose_name_plural": "Attribute Values",
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                blank=True, default="unknown-group", max_length=255, verbose_name="Slug"
            ),
        ),
        migrations.CreateModel(
            name="AttributeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Group Name")),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="attribute_groups",
                        to="goods.category",
                        verbose_name="Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute Group",
                "verbose_name_plural": "Attribute Groups",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="goods.attributegroup",
                verbose_name="Attribute Group",
            ),
        ),
    ]
