# Generated by Django 5.1.2 on 2024-11-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0016_alter_attribute_options_alter_attributevalue_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="goods/", verbose_name="Image"
                    ),
                ),
                ("description", models.TextField(max_length=100, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "good",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="goods.good",
                    ),
                ),
            ],
        ),
    ]
