# Generated by Django 5.1.2 on 2024-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
