# Generated by Django 5.1.2 on 2024-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0018_alter_productimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_filter",
            field=models.BooleanField(default=True),
        ),
    ]
