# Generated by Django 5.1.2 on 2024-11-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_order_total_price"),
        ("goods", "0016_alter_attribute_options_alter_attributevalue_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="goods.good",
            ),
        ),
    ]
