# Generated by Django 5.1.2 on 2024-11-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cartitem_cart_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cart.cart",
            ),
        ),
    ]
