# Generated by Django 5.1.2 on 2024-11-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_product_remove_order_cart_alter_orderitem_quantity_and_more"),
        ("goods", "0016_alter_attribute_options_alter_attributevalue_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="goods.good"
            ),
        ),
    ]
